import './globals.scss'
import { Inter } from 'next/font/google'
import { PrismicPreview } from '@prismicio/next'
import { cait, createClient } from '@/prismicio'
import Navigation from "@/components/layout/navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const client = createClient();

const globalSettings = await client.getSingle("global")

const {
  navigation_image,
  buttons,
  background_color
} = globalSettings.data || {};
console.log(globalSettings)
export default function RootLayout({ children }) {
  console.log(navigation_image)
  return (
    <html lang="en">
      <body>
        {globalSettings ? <Navigation buttons={buttons} navigationImage={navigation_image} backgroundColor={background_color} /> : null}
        {children}
        <PrismicPreview repositoryName={cait} />
      </body>
    </html>
  )
}